package main.java.de.avankziar.professionpro.newobjects.enums;

public enum PaymentOptionType
{
	MONEY, //Only Money
	PROFESSION_EXP, //Only Exp
	ITEM, //Only items/Loot
	VANILLA_EXP, //Only vanilla exp
	
	MONEY_AND_PROFESSIONEXP, //Both
	MONEY_OR_PROFESSIONEXP, //Only one from it
	MONEY_AND_ITEM,
	MONEY_OR_ITEM,
	MONEY_AND_VANILLAEXP,
	MONEY_OR_VANILLAEXP,
	PROFESSIONEXP_AND_ITEM,
	PROFESSIONEXP_OR_ITEM,
	PROFESSIONEXP_AND_VANILLAEXP,
	PROFESSIONEXP_OR_VANILLAEXP,
	ITEM_AND_VANILLAEXP,
	ITEM_OR_VANILLAEXP,
	
	MONEY_AND_PROFESSIONEXP_AND_ITEM,
	MONEY_OR_PROFESSIONEXP_OR_ITEM,
	MONEY_AND_PROFESSIONEXP_AND_VANILLAEXP,
	MONEY_OR_PROFESSIONEXP_OR_VANILLAEXP,
	MONEY_AND_ITEM_AND_VANILLAEXP,
	MONEY_OR_ITEM_OR_VANILLAEXP,
	PROFESSIONEXP_AND_ITEM_AND_VANILLAEXP,
	PROFESSIONEXP_OR_ITEM_OR_VANILLAEXP,
	
	ALL, //All together
	ONE_FROM_ALL, //Only one from it
	TWO_FROM_ALL, //Only two from it
	THREE_FROM_ALL, //Only three from it
	NONE; //None from all
}
